version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./dist:/opt/webcore/dist:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8123:80"
  build:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/opt/webcore
    command: npm run watch
    tty: true


